<?php

//определяет список возможных прав
function docviewer_perm() {
  return array("access docviewer content", "administer docviewer", "access docviewer source", "create docviewer nodes", "edit docviewer nodes");
}

//инициализация модуля
function docviever_init() {
}

//определение доступа к функциям
function docviewer_access($op, $node, $account) {
  if ($op == 'create') {
    return user_access('create docviewer nodes', $account);
  }
  if ($op == 'update' || $op == 'delete') {
    return user_access('edit docviewer nodes', $account);
  }
}

//вывод справки
function docviewer_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#docviewer":
      $output = '<p>'. t("Display interface for viewing docs (now only pdf)") .'</p>';
      break;
  }
  return $output;
}

//страница администрирования
function docviewer_admin() {
  $form = array();
  $form['docviewer_header'] = array(
    '#type' => 'textfield',
    '#title' => t('Default header'),
    '#default_value' => variable_get('docviewer_header', 'DocViewer'),
    '#size' => 20,
    '#maxlength' => 30,
    '#description' => t("Default header of document navigator"),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

//ссылка в меню
function docviewer_menu() {
  $items = array();
  $items['admin/settings/docviewer'] = array(
    'title' => t('DocViewer settings'),
    'description' => t('Settings for DocViewer'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('docviewer_admin'),
    'access arguments' => array('administer docviewer'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

//создание типа публикации
function docviewer_node_info() {
  return array(
    'docviewer_page' => array(
      'name' => t('page with document'),
      'module' => 'docviewer',
      'description' => "This is node with online viewer.",
    )
  );
}


